
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: fabricio
  password: luvi@1904


development:
  <<: *default
  database: store_notebooks_rails_development

test:
  <<: *default
  database: store_notebooks_rails_test

production:
  <<: *default
  database: store_notebooks_rails_production
  username: store_notebooks_rails
  password: <%= ENV['STORE_NOTEBOOKS_RAILS_DATABASE_PASSWORD'] %>
